const TeamList = [
    { 
        category: "executive", role: "President", name: "Anthony Sunjaya", 
        // email:"", linkedin:"", 
    },
    { category: "executive", role: "VP (Internal)", name: "Austin P. McDonald" },
    { category: "executive", role: "VP (External)", name: "Danielle Worton" },
    { category: "executive", role: "Secretary", name: "Nur Farah Karim" },
    { category: "executive", role: "Treasurer", name: "Cathleen Lee" },
    { category: "executive", role: "Arc Delegate", name: "Camelia Husswan" },
    { category: "directors", role: "Operations", name: "Priscilla Kwan" },
    { category: "directors", role: "Membership and Development", name: "Olivia Leung" },
    { category: "directors", role: "Finance and Partnership", name: "Danielle Worton" },
    { category: "directors", role: "Information Technology", name: "Arthur Wang" },
    { category: "directors", role: "Publications Director ", name: "Rachana Kheng" },
    { category: "directors", role: "Marketing Director", name: "Olivia Zheng" },
    { category: "associates", team: "Membership & Development", role: "M&D Associate", name: "Josephus Nifahowuo Ziraluo" },
    { category: "associates", team: "Membership & Development", role: "M&D Associate", name: "Yvonne Stiasny" },
    { category: "associates", team: "Membership & Development", role: "M&D Associate", name: "Chua Yi Jing" },
    { category: "associates", team: "Marketing", role: "Marketing Associate", name: "Cen Shen" },
    { category: "associates", team: "Marketing", role: "Marketing Associate", name: "Jessica Sutandar" },
    { category: "associates", team: "Marketing", role: "Marketing Associate", name: "Kevin Mandira Limanta" },
    { category: "associates", team: "Marketing", role: "Marketing Associate", name: "Sing-Sing Zhang" },
    { category: "associates", team: "Information Technology", role: "IT Associate", name: "Tim Zhang" },
    { category: "associates", team: "Information Technology", role: "IT Associate", name: "Emir Aditya Zen" },
    { category: "associates", team: "Information Technology", role: "IT Associate", name: "Hong Ze Zhang" },
    { category: "associates", team: "Information Technology", role: "IT Associate", name: "William Djong" },
    { category: "associates", team: "Information Technology", role: "IT Associate", name: "Fengyu Wang" },
    { category: "associates", team: "Operations", role: "Operations Associate", name: "Tin Arkar Maung" },
    { category: "associates", team: "Operations", role: "Operations Associate", name: "Charran Kethees" },
    { category: "associates", team: "Operations", role: "Operations Associate", name: "Eric Ryan Duong" },
    { category: "associates", team: "Operations", role: "Operations Associate", name: "Alexander Hekkenberg" },
    { category: "associates", team: "Finance & Partnership", role: "F&P Associate", name: "Christopher Chong Hong Chiok" },
    { category: "associates", team: "Finance & Partnership", role: "F&P Associate", name: "Kaung Hlaing" },
    { category: "associates", team: "Finance & Partnership", role: "F&P Associate", name: "Timothy Ng" },
];

export default TeamList;
