const TeamList = [
{ name: "Olivia Leung" },
{ name: "Paul Maxwell-Walters" },
{ name: "Amber Lov" },
{ name: "Joshua Yuan " },
{ name: "Joshua Yuan " },
{ name: "Julie Kim" },
{ name: "zami  lee" },
{ name: "Eliza Tang" },
{ name: "Kai Prikulis" },
{ name: "Cheryl Lam" },
{ name: "William Kou" },
{ name: "Finbar  Watson" },
{ name: "Timothy Rusmin" },
{ name: "Kim  Chen" },
{ name: "Daniel RESPALL" },
{ name: "Aaron Au" },
{ name: "Victoria Chin" },
{ name: "Tegan Smith" },
{ name: "Jade Kam" },
{ name: "Vaibhav Malhotra" },
{ name: "Austin McDonald" },
{ name: "David Duong" },
{ name: "Ke-Qing  Yap" },
{ name: "Ho Zuan Wong" },
{ name: "Emmanuel Katsigarakis" },
{ name: "Julian De Laffitte " },
{ name: "David Worton" },
{ name: "Zhuan Zhe  Lim" },
{ name: "Sevvel Senthil" },
{ name: "Ye Min  Oo" },
{ name: "Caroline Lee" },
{ name: "Roland Sebesfi" },
{ name: "Shihao Zhang" },
{ name: "Arthur Wang" },
{ name: "Shawn Le" },
{ name: "Alvin Sumadiredja" },
{ name: "Cathleen Lee" },
{ name: "James  Ting " },
{ name: "Xinyue Zhang" },
{ name: "Lucas Suhery" },
{ name: "Courtney Le" },
{ name: "Ketti Ketmontri" },
{ name: "Muhammad  Farhansyah " },
{ name: "Yixuan Shao" },
{ name: "Thuy Le" },
{ name: "Jason Lee" },
{ name: "Emma To" },
{ name: "Yuqing  Liu" },
{ name: "Amey Joshi" },
{ name: "Tom Chin" },
{ name: "Naman Goyal" },
{ name: "Timothy Ng" },
{ name: "Zoe Wrench" },
{ name: "Mowisha Danchaiviroj " },
{ name: "Khan Rahmat Ullah" },
{ name: "Alexandria Kim" },
{ name: "Liz Zhang" },
{ name: "Connor Sheng" },
{ name: "Chinmay Kalamkar" },
{ name: "Mowisha Danchaiviroj " },
{ name: "Jason Lee" },
{ name: "Connor Sheng" },
{ name: "Cathleen Lee" },
{ name: "Muhammad  Farhansyah " },
{ name: "Lucas Suhery" },
{ name: "Yixuan Shao" },
{ name: "Catherine Do" },
{ name: "Kiki Horas" },
{ name: "Yixuan Shao" },
]
export default TeamList;
